In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('01-tensor-operations')
jovian.set_colab_id('1_gvWugFYuheaUvQsi-nSb4GPV8YB96y0')

     |████████████████████████████████| 68 kB 2.8 MB/s 


> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Exploring PyTorch Operations

PyTorch is one the most popular library used for Deep Learning applications and here are some of its operations:

- `torch.linspace` - Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.
- `torch.eye` - Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.
- `torch.full` - Creates a tensor of size `size` filled with fill_value. The tensor’s dtype is inferred from fill_value.
- `torch.unbind` - Remove a tensor dimension
- `torch.clone` - Returns a copy of the tensor with the same size and data type.

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.linspace

Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.

In [4]:
# Example 1 - working
torch.linspace(2, 12, steps=6)

tensor([ 2.,  4.,  6.,  8., 10., 12.])

Here, we provide two integers. Start and end are the upper and lower limits, both inclusive and the `steps` define how many evenly spaced elements will be there in our tensor.

In [5]:
# Example 2 - working
torch.linspace(-100, 100, steps = 100)

tensor([-100.0000,  -97.9798,  -95.9596,  -93.9394,  -91.9192,  -89.8990,
         -87.8788,  -85.8586,  -83.8384,  -81.8182,  -79.7980,  -77.7778,
         -75.7576,  -73.7374,  -71.7172,  -69.6970,  -67.6768,  -65.6566,
         -63.6364,  -61.6162,  -59.5960,  -57.5758,  -55.5556,  -53.5354,
         -51.5152,  -49.4949,  -47.4747,  -45.4545,  -43.4343,  -41.4141,
         -39.3939,  -37.3737,  -35.3535,  -33.3333,  -31.3131,  -29.2929,
         -27.2727,  -25.2525,  -23.2323,  -21.2121,  -19.1919,  -17.1717,
         -15.1515,  -13.1313,  -11.1111,   -9.0909,   -7.0707,   -5.0505,
          -3.0303,   -1.0101,    1.0101,    3.0303,    5.0505,    7.0707,
           9.0909,   11.1111,   13.1313,   15.1515,   17.1717,   19.1919,
          21.2121,   23.2323,   25.2525,   27.2727,   29.2929,   31.3131,
          33.3333,   35.3535,   37.3737,   39.3939,   41.4141,   43.4343,
          45.4545,   47.4748,   49.4950,   51.5152,   53.5354,   55.5556,
          57.5758,   59.5960,   61.616

The range can be from negative numbers as well.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace(2, steps = 1000)

TypeError: ignored

All three parameters are needed for this to function properly.

We can use this function to generate a tensor of random numbers as per our specifications.

Let's save our work using Jovian before continuing.

In [9]:
!pip install jovian --upgrade --quiet

In [10]:
import jovian

In [11]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/rick101001/01-tensor-operations


'https://jovian.ai/rick101001/01-tensor-operations'

## Function 2 - torch.eye

Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [12]:
# Example 1 - working
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Returns a 5x5 matrix by row without the column parameter, having 1s on the diagonal and 0s elsewhere.

In [13]:
# Example 2 - working
torch.eye(5, 9)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.]])

The matrix does not have to be symmetric, can be according to any dimension we provide.

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
torch.eye(-1, -2)

RuntimeError: ignored

Dimensions have to be >= 0 for the matrix to be generated.

We can use this function in matrix operations.

In [15]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/rick101001/01-tensor-operations


'https://jovian.ai/rick101001/01-tensor-operations'

## Function 3 - torch.full

Creates a tensor of size size filled with fill_value. The tensor’s dtype is inferred from fill_value.

In [16]:
# Example 1 - working
torch.full((2, 3), -5)

tensor([[-5, -5, -5],
        [-5, -5, -5]])

Generates a matrix of 2x3 with -5 value.

In [20]:
# Example 2 - working
torch.full((2, 3, 4), -5)

tensor([[[-5, -5, -5, -5],
         [-5, -5, -5, -5],
         [-5, -5, -5, -5]],

        [[-5, -5, -5, -5],
         [-5, -5, -5, -5],
         [-5, -5, -5, -5]]])

Tensors of ANY dimensions >= 2 can be generated with this.

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
torch.full((2), 4)

TypeError: ignored

1D tensors can't be generated.

This function can also be used to generate dummy tensors for testing functions.

In [22]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/rick101001/01-tensor-operations


'https://jovian.ai/rick101001/01-tensor-operations'

## Function 4 - torch.unbind

Removes a tensor dimension.

Returns a tuple of all slices along a given dimension, already without it.

In [23]:
# Example 1 - working
torch.unbind(torch.tensor([[2, 3],
                           [4, 5],
                           [6,7]]))

(tensor([2, 3]), tensor([4, 5]), tensor([6, 7]))

Returned the tuple of separated tensors.

In [24]:
# Example 2 - working
torch.unbind(torch.tensor([[[2, 3],
                           [4, 5],
                           [6,7]]]))

(tensor([[2, 3],
         [4, 5],
         [6, 7]]),)

.unbind() only goes one level deep.

In [30]:
# Example 3 - breaking
torch.unbind(torch.tensor([2, 3],
                           [4, 5],
                           [6,7]))

TypeError: ignored

Needs a valid tensor for it to work

This can be used when dealing with high dimensional matrices in NNs to flatten them out later.

In [31]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/rick101001/01-tensor-operations


'https://jovian.ai/rick101001/01-tensor-operations'

## Function 5 - torch.clone

This returns a copy of the tensor with the same size and data type.

In [33]:
# Example 1 - working
a = torch.tensor([[2, 3],
              [4, 5], 
              [6, 7]])
b = a.clone()
a[1,0] = 9

b

tensor([[2, 3],
        [4, 5],
        [6, 7]])

Deep clones a tensor to avoid the problem of two tensors pointing to the same location when duplicated with x=y operation.

In [35]:
# Example 2 - working
a = torch.tensor([[[2, 3],
              [4, 5], 
              [6, 7]]])
b = a.clone()
a[0,1,0] = 9

b

tensor([[[2, 3],
         [4, 5],
         [6, 7]]])

Works with high dimensional tensors too.

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.tensor([2, 3],
              [4, 5], 
              [6, 7])
b = a.clone()


b

TypeError: ignored

Needs to be a valid tensor for this to work.

This can be used for deep cloning a tensor to avoid 2 tensors pointing to the same memory location when copied by x=y operation.

In [37]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/rick101001/01-tensor-operations


'https://jovian.ai/rick101001/01-tensor-operations'

## Conclusion

PyTorch is very pythonic in nature and can be configured according to the user's specifications as per the parameters given.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* [Some essential PyTorch functions to know:](https://towardsdatascience.com/useful-pytorch-functions-356de5f31a1e://)

In [38]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/rick101001/01-tensor-operations


'https://jovian.ai/rick101001/01-tensor-operations'